"use client";
import {useMemo,useState} from "react";
const OLD="https://mercado23y28-g7668nf5j-ernest196391s-projects.vercel.app";
const products=[
{id:1,n:"Leche entera",d:"1 litro",c:"Lácteos",p:800,img:OLD+"/products/leche.webp",tag:"Esencial"},
{id:2,n:"Yogur natural",d:"Vaso · 125 g",c:"Lácteos",p:350,img:"https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=700&q=80"},
{id:3,n:"Queso gouda",d:"Paquete · 500 g",c:"Lácteos",p:2100,img:"https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=700&q=80"},
{id:4,n:"Mantequilla",d:"Barra · 200 g",c:"Lácteos",p:950,img:"https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=700&q=80"},
{id:5,n:"Muslos de pollo",d:"Bandeja · 1 kg",c:"Carnes",p:2400,img:OLD+"/products/pollo.webp",tag:"Popular"},
{id:6,n:"Pechuga de pollo",d:"Bandeja · 1 kg",c:"Carnes",p:2850,img:"https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=700&q=80"},
{id:7,n:"Picadillo de res",d:"Paquete · 500 g",c:"Carnes",p:1950,img:"https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=700&q=80"},
{id:8,n:"Salchichas",d:"Paquete · 10 unidades",c:"Carnes",p:1200,img:"https://images.unsplash.com/photo-1612392062631-94dd858cba88?auto=format&fit=crop&w=700&q=80"},
{id:9,n:"Galletas con chocolate",d:"Paquete · 150 g",c:"Chucherías",p:550,img:OLD+"/products/galletas.webp"},
{id:10,n:"Caramelos surtidos",d:"Bolsa · 250 g",c:"Chucherías",p:500,img:"https://images.unsplash.com/photo-1581798459219-318e76aecc7b?auto=format&fit=crop&w=700&q=80"},
{id:11,n:"Papas fritas",d:"Bolsa · 150 g",c:"Chucherías",p:650,img:"https://images.unsplash.com/photo-1566478989037-eec170784d0b?auto=format&fit=crop&w=700&q=80"},
{id:12,n:"Chocolate con leche",d:"Tableta · 100 g",c:"Chucherías",p:700,img:"https://images.unsplash.com/photo-1575377427642-087cf684f29d?auto=format&fit=crop&w=700&q=80"},
{id:13,n:"Detergente líquido",d:"Botella · 3 litros",c:"Aseo",p:1100,img:OLD+"/products/detergente.webp",tag:"Ahorro"},
{id:14,n:"Jabón de baño",d:"Paquete · 3 unidades",c:"Aseo",p:600,img:"https://images.unsplash.com/photo-1607006483225-72c55a4b049b?auto=format&fit=crop&w=700&q=80"},
{id:15,n:"Pasta dental",d:"Tubo · 100 ml",c:"Aseo",p:550,img:"https://images.unsplash.com/photo-1559591937-e27a88c5e53b?auto=format&fit=crop&w=700&q=80"},
{id:16,n:"Champú familiar",d:"Botella · 750 ml",c:"Aseo",p:950,img:"https://images.unsplash.com/photo-1631729371254-42c2892f0e6e?auto=format&fit=crop&w=700&q=80"},
{id:17,n:"Aceite vegetal",d:"Botella · 1 litro",c:"Despensa",p:1400,img:OLD+"/products/aceite.webp",tag:"Esencial"},
{id:18,n:"Pasta penne",d:"Paquete · 500 g",c:"Despensa",p:600,img:OLD+"/products/pasta.webp"},
{id:19,n:"Arroz blanco",d:"Paquete · 1 kg",c:"Despensa",p:850,img:"https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=700&q=80"},
{id:20,n:"Frijoles negros",d:"Paquete · 1 kg",c:"Despensa",p:1000,img:"https://images.unsplash.com/photo-1551462147-ff29053bfc14?auto=format&fit=crop&w=700&q=80"}];
const cats=["Todos","Lácteos","Carnes","Chucherías","Aseo","Despensa"];
const money=n=>new Intl.NumberFormat("es-CU").format(n)+" CUP";
function answerFor(q){const s=q.toLowerCase();if(s.includes("pollo")||s.includes("carne"))return"Para una comida familiar te recomiendo los muslos de pollo. Puedes acompañarlos con arroz y aceite.";if(s.includes("desay")||s.includes("leche"))return"Para el desayuno tienes leche, yogur, mantequilla y galletas. Puedo ayudarte a añadirlos.";if(s.includes("aseo")||s.includes("limpieza"))return"En aseo tenemos detergente, jabón, pasta dental y champú. El detergente está marcado como opción de ahorro.";if(s.includes("barato")||s.includes("económ"))return"Las opciones más económicas son yogur natural, caramelos, jabón y pasta dental.";if(s.includes("entrega")||s.includes("domicilio"))return"Al terminar tu compra podrás elegir recogida en el mercado o entrega a domicilio. El costo se confirma antes de enviar el pedido.";if(s.includes("ubic")||s.includes("direc"))return"Estamos en la esquina de 23 y 28, Vedado, La Habana.";if(s.includes("horario"))return"El horario definitivo se confirmará con el mercado. Por ahora puedes preparar tu carrito a cualquier hora.";return"Puedo recomendarte productos, buscar opciones económicas, ayudarte con una comida o explicarte cómo recoger o pedir entrega."}
export default function Home(){
const[cat,setCat]=useState("Todos"),[query,setQuery]=useState(""),[cart,setCart]=useState({}),[drawer,setDrawer]=useState(false),[chat,setChat]=useState(false),[detail,setDetail]=useState(null),[msg,setMsg]=useState(""),[messages,setMessages]=useState([{who:"bot",text:"¡Hola! Soy Mercadito. ¿Qué necesitas comprar hoy?"}]);
const filtered=useMemo(()=>products.filter(x=>(cat==="Todos"||x.c===cat)&&((x.n+" "+x.d+" "+x.c).toLowerCase().includes(query.toLowerCase()))),[cat,query]);
const count=Object.values(cart).reduce((a,b)=>a+b,0),total=products.reduce((a,p)=>a+(cart[p.id]||0)*p.p,0);
const add=id=>setCart(x=>({...x,[id]:(x[id]||0)+1}));
const change=(id,v)=>setCart(x=>{const n={...x};if(v<=0)delete n[id];else n[id]=v;return n});
const send=preset=>{const text=(preset||msg).trim();if(!text)return;setMessages(m=>[...m,{who:"user",text},{who:"bot",text:answerFor(text)}]);setMsg("")};
const listen=()=>{const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){setMessages(m=>[...m,{who:"bot",text:"Tu navegador no permite dictado. Puedes escribirme aquí."}]);return}const r=new R();r.lang="es-ES";r.onresult=e=>setMsg(e.results[0][0].transcript);r.start()};
return <div><div className="testbar">CATÁLOGO DE DEMOSTRACIÓN · PRECIOS ILUSTRATIVOS</div>
<header><div className="top"><a className="brand" href="#"><img src={OLD+"/brand/isotipo.png"} alt="Mercado 23 y 28"/><span><b>MERCADO<br/>23 Y 28</b><small>Tu vecino de confianza</small></span></a><label className="search"><span>⌕</span><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="¿Qué necesitas hoy?"/></label><button className="cartBtn" onClick={()=>setDrawer(true)}>🛒 <span>Mi carrito</span><b>{count}</b></button></div><nav>{cats.map(x=><button className={cat===x?"active":""} onClick={()=>{setCat(x);document.querySelector("#productos")?.scrollIntoView({behavior:"smooth"})}} key={x}>{x==="Todos"?"Productos":x}</button>)}<a href="#como">Cómo comprar</a><a href="#contacto">Ubicación</a></nav></header>
<main><section className="hero"><div className="heroCopy"><span className="eyebrow">EN EL CORAZÓN DEL VEDADO</span><h1>Tu vecino<br/><em>de confianza.</em></h1><p>Tu compra del día, más cerca.<br/>Elige, añade y prepara tu pedido desde el móvil.</p><button onClick={()=>document.querySelector("#productos").scrollIntoView({behavior:"smooth"})}>Comprar ahora →</button></div><div className="heroImg"><img src={OLD+"/brand/fachada.jpg"} alt="Fachada del Mercado 23 y 28"/><span>📍 23 y 28 · La Habana</span></div></section>
<section className="categories"><div className="title"><div><span className="eyebrow">COMPRA POR CATEGORÍA</span><h2>¿Qué llevamos hoy?</h2></div><button onClick={()=>setCat("Todos")}>Ver todo →</button></div><div className="catgrid">{cats.slice(1).map(x=>{const p=products.find(z=>z.c===x);return <button className={cat===x?"chosen":""} onClick={()=>{setCat(x);document.querySelector("#productos").scrollIntoView({behavior:"smooth"})}} key={x}><img src={p.img} alt=""/><b>{x}</b></button>})}</div></section>
<section id="productos" className="catalog"><div className="title"><div><span className="eyebrow">PARA TU COMPRA</span><h2>{query?"Resultados de búsqueda":cat==="Todos"?"Un poquito de todo":cat}</h2></div><span>{filtered.length} productos</span></div>{filtered.length?<div className="grid">{filtered.map(p=><article className="card" key={p.id}>{p.tag&&<span className="tag">{p.tag}</span>}<button className="photo" onClick={()=>setDetail(p)}><img src={p.img} alt={p.n}/></button><div className="copy"><small>{p.c}</small><button className="name" onClick={()=>setDetail(p)}>{p.n}</button><p>{p.d}</p><strong>{money(p.p)}</strong><span className="sample">Precio de prueba</span><button className="add" onClick={()=>add(p.id)}>＋ Añadir</button></div></article>)}</div>:<div className="empty"><b>No encontramos ese producto.</b><p>Prueba otra palabra o pregúntale a Mercadito.</p><button onClick={()=>setChat(true)}>Hablar con el asistente</button></div>}</section>
<section id="como" className="how"><div><span className="eyebrow">ASÍ DE FÁCIL</span><h2>Tu compra, a tu manera.</h2><p>Prepara el pedido en tres pasos.</p></div>{[["1","Elige tus productos","Añade al carrito y ajusta las cantidades."],["2","Recoge o pide entrega","Escoge la opción que mejor te funcione."],["3","Revisa y confirma","Comprueba el resumen antes de enviarlo."]].map(x=><article key={x[0]}><i>{x[0]}</i><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</section></main>
<footer id="contacto"><div><b>Mercado 23 y 28</b><p>Tu vecino de confianza.</p></div><p>📍 23 y 28, Vedado<br/>La Habana, Cuba</p><a href="https://www.instagram.com/mercado23y28/" target="_blank">Instagram →</a><small>Catálogo de demostración: productos, imágenes y precios ilustrativos.</small></footer>
<button className="assistantFab" onClick={()=>setChat(true)}><span>✨</span><b>Pregúntale a Mercadito</b></button>
{drawer&&<div className="overlay" onClick={()=>setDrawer(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawerHead"><div><small>TU COMPRA</small><h2>Mi carrito</h2></div><button onClick={()=>setDrawer(false)}>×</button></div>{!count?<div className="emptyCart">🛒<h3>Tu carrito está vacío</h3><p>Añade algo rico para comenzar.</p><button onClick={()=>setDrawer(false)}>Ver productos</button></div>:<><div className="cartList">{products.filter(p=>cart[p.id]).map(p=><div className="cartItem" key={p.id}><img src={p.img} alt=""/><div><b>{p.n}</b><small>{money(p.p)}</small><div className="qty"><button onClick={()=>change(p.id,cart[p.id]-1)}>−</button><span>{cart[p.id]}</span><button onClick={()=>change(p.id,cart[p.id]+1)}>＋</button></div></div><strong>{money(p.p*cart[p.id])}</strong></div>)}</div><div className="checkout"><div><span>Subtotal</span><b>{money(total)}</b></div><small>La entrega y disponibilidad se confirman al tramitar el pedido.</small><button onClick={()=>alert("Demostración lista. El canal real de confirmación se conectará con los datos del mercado.")}>Continuar pedido</button></div></>}</aside></div>}
{detail&&<div className="overlay modalWrap" onClick={()=>setDetail(null)}><section className="detail" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setDetail(null)}>×</button><img src={detail.img} alt=""/><div><small>{detail.c}</small><h2>{detail.n}</h2><p>{detail.d}</p><strong>{money(detail.p)}</strong><span>Precio de prueba</span><button onClick={()=>{add(detail.id);setDetail(null)}}>Añadir al carrito</button></div></section></div>}
{chat&&<div className="chat"><div className="chatHead"><div><span>✨</span><div><b>Mercadito</b><small>Asistente del mercado</small></div></div><button onClick={()=>setChat(false)}>×</button></div><div className="messages">{messages.map((m,i)=><p className={m.who} key={i}>{m.text}</p>)}</div><div className="chips">{["¿Qué compro para desayunar?","Busco algo económico","¿Cómo funciona la entrega?"].map(x=><button onClick={()=>send(x)} key={x}>{x}</button>)}</div><div className="composer"><button onClick={listen} aria-label="Dictar">🎙️</button><input value={msg} onChange={e=>setMsg(e.target.value)} onKeyDown={e=>e.key==="Enter"&&send()} placeholder="Escribe tu pregunta"/><button onClick={()=>send()}>➤</button></div></div>}</div>}
