"use client";
import {useEffect,useRef,useState} from "react";
import {money} from "../lib/commerce.mjs";
function Glyph({name}){return <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" aria-hidden="true">{name==="whatsapp"?<><path d="M12 2a10 10 0 0 0-8.7 15L2 22l5-1.3A10 10 0 1 0 12 2Z"/><path d="M8 7c-2 4 3 9 7 9l2-2-3-2-1 1-3-3 1-1-2-3Z"/></>:name==="mic"?<><rect x="9" y="2" width="6" height="12" rx="3"/><path d="M5 10a7 7 0 0 0 14 0M12 17v5"/></>:name==="camera"?<><path d="M3 7h5l2-3h4l2 3h5v14H3Z"/><circle cx="12" cy="13" r="3"/></>:name==="attach"?<path d="m20 11-8 8a5 5 0 0 1-7-7l9-9a3 3 0 0 1 4 4l-9 9a1 1 0 0 1-2-2l8-8"/>:<path d="m3 3 18 9-18 9 4-9-4-9Zm4 9h14"/>}</svg>}
export default function Support({onAdd}){
const [config,setConfig]=useState(null),[open,setOpen]=useState(false),[q,setQ]=useState(""),[files,setFiles]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[messages,setMessages]=useState([]),[recording,setRecording]=useState(false);
const launcher=useRef(null),panel=useRef(null),end=useRef(null),recognition=useRef(null);
useEffect(()=>{fetch("/api/commerce/config").then(r=>r.json()).then(setConfig).catch(()=>setError("No pudimos cargar la configuración."));return()=>recognition.current?.abort()},[]);
useEffect(()=>{if(open)panel.current?.focus();else launcher.current?.focus()},[open]);
useEffect(()=>{end.current?.scrollIntoView({block:"nearest"})},[messages,busy]);
function close(){recognition.current?.abort();setOpen(false)}
function keys(e){if(e.key==="Escape")close();if(e.key==="Tab"){const list=[...panel.current.querySelectorAll('button:not(:disabled), a[href], input:not(:disabled), textarea:not(:disabled)')].filter(x=>x.getClientRects().length);if(!list.length)return;const first=list[0],last=list.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===panel.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}
function addFiles(list){const next=[...files,...Array.from(list||[])];if(next.length>3||next.reduce((s,f)=>s+f.size,0)>3000000){setError("Hasta 3 archivos y 3 MB en total.");return}setFiles(next);setError("")}
async function send(e){e.preventDefault();if(busy||(!q.trim()&&!files.length))return;setBusy(true);setError("");const form=new FormData();form.set("question",q);form.set("history",JSON.stringify(messages.slice(-8)));files.forEach(f=>form.append("attachments",f));const sent=q||"Consulta con adjuntos";
try{const r=await fetch("/api/assistant/chat",{method:"POST",body:form,signal:AbortSignal.timeout(55000)}),data=await r.json();if(!r.ok)throw Error(data.error||"No pude responder.");setMessages(m=>[...m,{role:"user",text:sent},{role:"assistant",text:data.answer,products:data.products}]);setQ("");setFiles([])}catch(e){setError(e.name==="TimeoutError"?"La consulta tardó demasiado. Puedes reintentar.":e.message)}finally{setBusy(false)}}
function dictate(){if(recording){recognition.current?.stop();return}const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){setError("Este navegador no admite dictado. Puedes escribir tu consulta.");return}const r=new R();recognition.current=r;r.lang="es-ES";r.onresult=e=>setQ(v=>v+" "+e.results[0][0].transcript);r.onerror=()=>{setError("No pudimos usar el micrófono. Revisa el permiso del navegador.");setRecording(false)};r.onend=()=>setRecording(false);try{r.start();setRecording(true)}catch{setError("El micrófono no está disponible.")}}
return <><div className="supportDock"><button ref={launcher} className="bessyLaunch" aria-label="Abrir Veci" aria-expanded={open} onClick={()=>setOpen(true)}>{config?.avatar?<img src={config.avatar} alt="Veci"/>:"Veci"}</button>{config?.whatsapp?<a className="waLaunch" href={config.whatsapp} target="_blank" rel="noopener noreferrer" aria-label="WhatsApp de Mercado 23 y 28"><Glyph name="whatsapp"/></a>:<button className="waLaunch" aria-label="WhatsApp pendiente de configurar" onClick={()=>{setOpen(true);setError("El mercado todavía no ha configurado su número de WhatsApp.")}}><Glyph name="whatsapp"/></button>}</div>
{open&&<div className="bessyBackdrop" onClick={close}><section ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-label="Veci, asistente de Mercado 23 y 28" className="bessyPanel" onClick={e=>e.stopPropagation()} onKeyDown={keys}><div className="bessyHeader"><div><b>Veci</b><small>Mercado 23 y 28</small></div><button onClick={close} aria-label="Cerrar Veci">×</button></div><div className="bessyMessages" aria-live="polite"><p>{config?.assistantReady?"Hola. Puedo ayudarte a buscar productos, comparar opciones y preparar tu compra.":"La conexión de Veci está pendiente de activación. El catálogo y el carrito siguen disponibles."}</p>{messages.map((m,i)=><article key={i} className={m.role}><p>{m.text}</p>{m.products?.map(p=><div className="bessyProduct" key={p.id}><img src={p.img} alt=""/><div><b>{p.n}</b><p>{p.d} · {money(p.p)}</p><button onClick={()=>onAdd(p.id)}>Añadir al carrito</button></div></div>)}</article>)}{busy&&<p role="status">Veci está consultando…</p>}<div ref={end}/></div>
{error&&<p className="bessyError" role="alert">{error}</p>}
<form className="bessyComposer" onSubmit={send}><label htmlFor="bessy-q">Tu consulta</label><textarea id="bessy-q" maxLength={1000} value={q} onChange={e=>setQ(e.target.value)} placeholder="¿Qué necesitas hoy?"/>{files.map((f,i)=><div key={i}>{f.name}<button type="button" aria-label={"Quitar "+f.name} onClick={()=>setFiles(v=>v.filter((_,n)=>n!==i))}>×</button></div>)}<div className="bessyTools"><label className="fileControl" aria-label="Adjuntar archivo"><Glyph name="attach"/><input type="file" multiple accept=".jpg,.jpeg,.png,.webp,.pdf,.txt" onChange={e=>{addFiles(e.target.files);e.target.value=""}}/></label><label className="fileControl" aria-label="Tomar foto"><Glyph name="camera"/><input type="file" capture="environment" accept="image/jpeg,image/png,image/webp" onChange={e=>{addFiles(e.target.files);e.target.value=""}}/></label><button type="button" aria-label={recording?"Detener dictado":"Dictar consulta"} onClick={dictate}><Glyph name="mic"/>{recording?"Detener":""}</button><button type="submit" disabled={busy||!config?.assistantReady} aria-label="Enviar consulta"><Glyph name="send"/></button></div></form></section></div>}</>}
