"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {money} from "../lib/commerce.mjs";
function Glyph({name}){return <svg width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">{name==="whatsapp"?<><path d="M12 2a10 10 0 0 0-8.7 15L2 22l5-1.3A10 10 0 1 0 12 2Z"/><path d="M8 7c-2 4 3 9 7 9l2-2-3-2-1 1-3-3 1-1-2-3Z"/></>:name==="mic"?<><rect x="9" y="2" width="6" height="12" rx="3"/><path d="M5 10a7 7 0 0 0 14 0M12 17v5"/></>:name==="camera"?<><path d="M3 7h5l2-3h4l2 3h5v14H3Z"/><circle cx="12" cy="13" r="3"/></>:name==="attach"?<path d="m20 11-8 8a5 5 0 0 1-7-7l9-9a3 3 0 0 1 4 4l-9 9a1 1 0 0 1-2-2l8-8"/>:name==="search"?<><circle cx="10" cy="10" r="6"/><path d="m15 15 6 6"/></>:name==="cart"?<><path d="M3 3h2l3 12h11l2-9H6"/><circle cx="9" cy="20" r="1"/><circle cx="18" cy="20" r="1"/></>:name==="truck"?<><path d="M3 6h11v10H3zM14 10h4l3 3v3h-7z"/><circle cx="7" cy="18" r="2"/><circle cx="18" cy="18" r="2"/></>:name==="shop"?<><path d="M4 10v10h16V10M3 10l2-5h14l2 5M8 20v-6h8v6"/></>:<path d="m3 3 18 9-18 9 4-9-4-9Zm4 9h14"/>}</svg>}
export default function Support({onAdd,cart={}}){
const [config,setConfig]=useState(null),[open,setOpen]=useState(false),[q,setQ]=useState(""),[files,setFiles]=useState([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[messages,setMessages]=useState([]),[recording,setRecording]=useState(false),[cameraOpen,setCameraOpen]=useState(false),[stream,setStream]=useState(null);
const launcher=useRef(null),panel=useRef(null),end=useRef(null),recognition=useRef(null),videoRef=useRef(null),cameraInput=useRef(null);
useEffect(()=>{fetch("/api/commerce/config").then(r=>r.json()).then(setConfig).catch(()=>setError("No pudimos cargar la configuración."));return()=>{recognition.current?.abort();stream?.getTracks().forEach(t=>t.stop())}},[stream]);
useEffect(()=>{if(open)panel.current?.focus();else launcher.current?.focus()},[open]);
useEffect(()=>{end.current?.scrollIntoView({block:"nearest"})},[messages,busy]);
useEffect(()=>{if(cameraOpen&&videoRef.current&&stream)videoRef.current.srcObject=stream},[cameraOpen,stream]);
const previews=useMemo(()=>files.map(f=>f.type?.startsWith("image/")?URL.createObjectURL(f):null),[files]);
useEffect(()=>()=>previews.forEach(u=>u&&URL.revokeObjectURL(u)),[previews]);
const cartCount=useMemo(()=>Object.values(cart||{}).reduce((a,b)=>a+b,0),[cart]);
function stopCamera(){stream?.getTracks().forEach(t=>t.stop());setStream(null);setCameraOpen(false)}
function close(){recognition.current?.abort();stopCamera();setOpen(false)}
function keys(e){if(e.key==="Escape")close();if(e.key==="Tab"){const list=[...panel.current.querySelectorAll('button:not(:disabled), a[href], input:not(:disabled), textarea:not(:disabled)')].filter(x=>x.getClientRects().length);if(!list.length)return;const first=list[0],last=list.at(-1);if(e.shiftKey&&(document.activeElement===first||document.activeElement===panel.current)){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}
function addFiles(list){const incoming=Array.from(list||[]),next=[...files,...incoming];if(next.length>3||next.reduce((s,f)=>s+f.size,0)>3000000){setError("Hasta 3 archivos y 3 MB en total.");return}setFiles(next);setError("")}
async function openCamera(){setError("");try{if(!navigator.mediaDevices?.getUserMedia)throw Error("NO_CAMERA");const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}},audio:false});setStream(s);setCameraOpen(true)}catch{cameraInput.current?.click()}}
function takePhoto(){const v=videoRef.current;if(!v?.videoWidth)return;const c=document.createElement("canvas");c.width=v.videoWidth;c.height=v.videoHeight;c.getContext("2d").drawImage(v,0,0);c.toBlob(blob=>{if(blob){addFiles([new File([blob],"foto-veci.jpg",{type:"image/jpeg"})]);stopCamera()}},"image/jpeg",.9)}
async function ask(text,attachments=files){const question=(text??q).trim();if(busy||(!question&&!attachments.length))return;setBusy(true);setError("");const form=new FormData();form.set("question",question);form.set("history",JSON.stringify(messages.slice(-8).map(x=>({role:x.role,text:x.text}))));attachments.forEach(f=>form.append("attachments",f));const localAttachments=attachments.map((f,i)=>({name:f.name,url:f.type?.startsWith("image/")?URL.createObjectURL(f):null}));setMessages(m=>[...m,{role:"user",text:question||"Consulta con foto",attachments:localAttachments}]);try{const r=await fetch("/api/assistant/chat",{method:"POST",body:form,signal:AbortSignal.timeout(55000)});let data={};try{data=await r.json()}catch{}if(!r.ok)throw Error(data.error||"Veci no pudo responder ahora.");setMessages(m=>[...m,{role:"assistant",text:data.answer,products:data.products}]);setQ("");setFiles([])}catch(e){setError(e.name==="TimeoutError"?"La consulta tardó demasiado. Puedes reintentar.":e.message)}finally{setBusy(false)}}
function send(e){e.preventDefault();ask()}
function dictate(){if(recording){recognition.current?.stop();return}const R=window.SpeechRecognition||window.webkitSpeechRecognition;if(!R){setError("Este navegador no admite dictado. Puedes escribir tu consulta.");return}const r=new R();recognition.current=r;r.lang="es-ES";r.onresult=e=>setQ(v=>(v+" "+e.results[0][0].transcript).trim());r.onerror=()=>{setError("No pudimos usar el micrófono. Revisa el permiso del navegador.");setRecording(false)};r.onend=()=>setRecording(false);try{r.start();setRecording(true)}catch{setError("El micrófono no está disponible.")}}
const avatar="/brand/veci-avatar.svg";
const quick=[["search","Buscar productos","Encuentra lo que necesitas","Quiero buscar productos del catálogo."],["cart","Armar compra","Te ayudo paso a paso","Ayúdame a armar una compra. Pregúntame primero para qué la necesito y mi presupuesto."],["truck","Envío","Consulta zonas y precios","Quiero saber el costo de mensajería. Pregúntame municipio y localidad si hace falta."],["shop","Recoger en tienda","Compra online y recoge","Explícame cómo funciona recoger mi compra en Mercado 23 y 28."]];
return <div className="veciV2"><div className="supportDock"><button ref={launcher} className="bessyLaunch" aria-label="Abrir Veci" aria-expanded={open} onClick={()=>setOpen(true)}><img src={avatar} alt="Veci"/></button>{config?.whatsapp&&<a className="waLaunch" href={config.whatsapp} target="_blank" rel="noopener noreferrer" aria-label="WhatsApp de Mercado 23 y 28"><Glyph name="whatsapp"/></a>}</div>
{open&&<div className="bessyBackdrop" onClick={close}><section ref={panel} tabIndex={-1} role="dialog" aria-modal="true" aria-label="Veci, asistente de Mercado 23 y 28" className="bessyPanel" onClick={e=>e.stopPropagation()} onKeyDown={keys}><div className="bessyBrandBar"><div><strong>Mercado 23 y 28</strong><span> · Tu vecino de confianza</span></div><button className="bessyClose" onClick={close} aria-label="Cerrar Veci">×</button></div><div className="bessyIdentity"><div className="bessyAvatar"><img src={avatar} alt="Veci"/></div><div><b>Veci</b><small className="bessyOnline">● En línea</small><small>Asistente de Mercado 23 y 28</small></div></div><div className="bessyMessages" aria-live="polite"><p><b>¡Hola! Soy Veci 👋</b><br/>¿Qué necesitas hoy?</p><p>Puedo ayudarte a buscar productos, armar tu compra, ver opciones de envío o resolver cualquier duda.</p>{cartCount>0&&<div className="bessyCartStrip"><span>🛒 {cartCount} {cartCount===1?"producto":"productos"} en tu carrito</span><a href="/checkout">Revisar pedido →</a></div>}{messages.map((m,i)=><article key={i} className={m.role}><p>{m.text}</p>{m.attachments?.some(a=>a.url)&&<div className="bessyMessageMedia">{m.attachments.filter(a=>a.url).map((a,n)=><img key={n} src={a.url} alt="Foto enviada a Veci"/>)}</div>}{m.products?.length>0&&<><div className="bessyProductGrid">{m.products.map(p=><div className="bessyProduct" key={p.id}><img src={p.img} alt={p.n}/><div><b>{p.n}</b><p>{p.d}<br/>{money(p.p)}</p><button onClick={()=>onAdd(p.id)}>Añadir al carrito</button></div></div>)}</div>{m.products.length>1&&<button className="bessyMultiAdd" onClick={()=>m.products.forEach(p=>onAdd(p.id))}>Añadir todos</button>}</>}</article>)}{busy&&<p className="bessyTyping" role="status">Veci está buscando…</p>}<div ref={end}/></div>
{messages.length===0&&<div className="bessyQuick">{quick.map(([icon,title,sub,prompt])=><button key={title} type="button" onClick={()=>ask(prompt,[])}><Glyph name={icon}/><span>{title}<small>{sub}</small></span></button>)}{config?.whatsapp&&<a className="whatsappAction" href={config.whatsapp} target="_blank" rel="noopener noreferrer"><Glyph name="whatsapp"/> Confirmar por WhatsApp<small>Continúa tu compra con una persona</small></a>}</div>}
{error&&<p className="bessyError" role="alert">{error}</p>}
<form className="bessyComposer" onSubmit={send}><label htmlFor="bessy-q">Tu consulta</label><textarea id="bessy-q" maxLength={1000} value={q} onChange={e=>setQ(e.target.value)} placeholder="Escribe tu mensaje..."/>{files.length>0&&<div className="bessyFiles">{files.map((f,i)=><div className="bessyFilePreview" key={i}>{previews[i]?<img src={previews[i]} alt="Vista previa"/>:<span>{f.name}</span>}<button type="button" aria-label={"Quitar "+f.name} onClick={()=>setFiles(v=>v.filter((_,n)=>n!==i))}>×</button></div>)}</div>}<div className="bessyTools"><label className="fileControl" aria-label="Adjuntar archivo"><Glyph name="attach"/><input type="file" multiple accept=".jpg,.jpeg,.png,.webp,.pdf,.txt" onChange={e=>{addFiles(e.target.files);e.target.value=""}}/></label><button className="cameraControl" type="button" aria-label="Abrir cámara" onClick={openCamera}><Glyph name="camera"/></button><input ref={cameraInput} className="hiddenCameraInput" type="file" capture="environment" accept="image/*" onChange={e=>{addFiles(e.target.files);e.target.value=""}}/><button type="button" aria-label={recording?"Detener dictado":"Dictar consulta"} onClick={dictate}><Glyph name="mic"/></button><button type="submit" disabled={busy||!config?.assistantReady} aria-label="Enviar consulta"><Glyph name="send"/></button></div></form><div className="bessyTagline">Buenas compras, mejores vecinos ♡</div>{cameraOpen&&<div className="veciCamera"><video ref={videoRef} autoPlay playsInline muted/><div><button type="button" onClick={stopCamera}>Cancelar</button><button type="button" className="cameraShot" onClick={takePhoto}>Tomar foto</button></div></div>}</section></div>}</div>}
