export const products=[
{id:1,n:"Leche entera",d:"1 litro",c:"Lácteos",p:800,img:"/products/leche.svg",tag:"Esencial"},
{id:2,n:"Leche en polvo",d:"Bolsa · 400 g",c:"Lácteos",p:2600,img:"/products/leche-polvo.svg"},
{id:3,n:"Yogur natural",d:"Vaso · 125 g",c:"Lácteos",p:350,img:"/products/yogur-natural.svg"},
{id:4,n:"Yogur bebible de fresa",d:"Botella · 1 litro",c:"Lácteos",p:900,img:"/products/yogur-bebible.svg"},
{id:5,n:"Queso gouda",d:"Paquete · 500 g",c:"Lácteos",p:2100,img:"/products/queso-gouda.svg"},
{id:6,n:"Queso crema",d:"Pote · 200 g",c:"Lácteos",p:1800,img:"/products/queso-crema.svg"},
{id:7,n:"Mantequilla",d:"Barra · 200 g",c:"Lácteos",p:950,img:"/products/mantequilla.svg"},
{id:8,n:"Muslos de pollo",d:"Bandeja · 1 kg",c:"Carnes",p:2400,img:"/products/pollo-muslos.svg",tag:"Popular"},
{id:9,n:"Pechuga de pollo",d:"Bandeja · 1 kg",c:"Carnes",p:2850,img:"/products/pollo-pechuga.svg"},
{id:10,n:"Picadillo de res",d:"Paquete · 500 g",c:"Carnes",p:1950,img:"/products/picadillo-res.svg"},
{id:11,n:"Salchichas",d:"Paquete · 10 unidades",c:"Carnes",p:1200,img:"/products/salchichas.svg"},
{id:12,n:"Perritos calientes",d:"Paquete · 8 unidades",c:"Carnes",p:1300,img:"/products/perritos-calientes.svg"},
{id:13,n:"Jamón de cerdo",d:"Paquete · 300 g",c:"Carnes",p:2200,img:"/products/jamon-cerdo.svg"},
{id:14,n:"Costillas de cerdo",d:"Bandeja · 1 kg",c:"Carnes",p:2600,img:"/products/costillas-cerdo.svg"},
{id:15,n:"Galletas con chocolate",d:"Paquete · 150 g",c:"Chucherías",p:550,img:"/products/galletas-chocolate.svg"},
{id:16,n:"Galletas saladas",d:"Paquete · 200 g",c:"Chucherías",p:500,img:"/products/galletas-saladas.svg"},
{id:17,n:"Caramelos surtidos",d:"Bolsa · 250 g",c:"Chucherías",p:500,img:"/products/caramelos.svg"},
{id:18,n:"Papas fritas",d:"Bolsa · 150 g",c:"Chucherías",p:650,img:"/products/papas-fritas.svg"},
{id:19,n:"Chocolate con leche",d:"Tableta · 100 g",c:"Chucherías",p:700,img:"/products/chocolate.svg"},
{id:20,n:"Barra de cereal",d:"Paquete · 6 unidades",c:"Chucherías",p:450,img:"/products/barra-cereal.svg"},
{id:21,n:"Detergente líquido",d:"Botella · 3 litros",c:"Aseo",p:1100,img:"/products/detergente-liquido.svg",tag:"Ahorro"},
{id:22,n:"Detergente en polvo",d:"Bolsa · 1 kg",c:"Aseo",p:1300,img:"/products/detergente-polvo.svg"},
{id:23,n:"Jabón de baño",d:"Paquete · 3 unidades",c:"Aseo",p:600,img:"/products/jabon-bano.svg"},
{id:24,n:"Pasta dental",d:"Tubo · 100 ml",c:"Aseo",p:550,img:"/products/pasta-dental.svg"},
{id:25,n:"Champú familiar",d:"Botella · 750 ml",c:"Aseo",p:950,img:"/products/champu.svg"},
{id:26,n:"Papel higiénico",d:"Paquete · 4 rollos",c:"Aseo",p:700,img:"/products/papel-higienico.svg"},
{id:27,n:"Aceite vegetal",d:"Botella · 1 litro",c:"Despensa",p:1400,img:"/products/aceite.svg",tag:"Esencial"},
{id:28,n:"Pasta penne",d:"Paquete · 500 g",c:"Despensa",p:600,img:"/products/pasta-penne.svg"},
{id:29,n:"Arroz blanco",d:"Paquete · 1 kg",c:"Despensa",p:850,img:"/products/arroz.svg"},
{id:30,n:"Frijoles negros",d:"Paquete · 1 kg",c:"Despensa",p:1000,img:"/products/frijoles.svg"},
{id:31,n:"Azúcar blanca",d:"Paquete · 1 kg",c:"Despensa",p:750,img:"/products/azucar.svg"},
{id:32,n:"Café molido",d:"Paquete · 250 g",c:"Despensa",p:1600,img:"/products/cafe.svg"},
{id:33,n:"Huevos",d:"Cartón · 30 unidades",c:"Despensa",p:2200,img:"/products/huevos.svg"}
];
