export const products=[
{id:1,n:"Hamburguesas congeladas",d:"Karmac · Paquete 500 g · 6 unidades",c:"Carnes y Embutidos",p:780,img:"/products/hamburguesas-congeladas.webp"},
{id:2,n:"Albóndigas congeladas",d:"Karmac · Bolsa",c:"Carnes y Embutidos",p:7300,img:"/products/albondigas-congeladas.webp"},
{id:3,n:"Carne de cerdo",d:"Bandeja",c:"Carnes y Embutidos",p:3500,img:"/products/cerdo-bandeja.webp"},
{id:4,n:"Carne de cerdo",d:"Bandeja grande",c:"Carnes y Embutidos",p:4900,img:"/products/cerdo-bandeja-grande.webp"},
{id:5,n:"Cerdo en pieza",d:"Pieza",c:"Carnes y Embutidos",p:11900,img:"/products/cerdo-pieza.svg"},
{id:6,n:"Carne congelada (corte por confirmar)",d:"Pieza grande",c:"Carnes y Embutidos",p:6000,img:"/products/carne-corte-confirmar.svg"},
{id:7,n:"Carne en bandeja (corte por confirmar)",d:"Bandeja",c:"Carnes y Embutidos",p:3500,img:"/products/carne-bandeja-confirmar.svg"},
{id:8,n:"Embutido largo",d:"Pieza",c:"Carnes y Embutidos",p:5200,img:"/products/embutido-largo.webp"},
{id:9,n:"Salchichón",d:"Pieza en lonchas",c:"Carnes y Embutidos",p:3800,img:"/products/salchichon.webp"},
{id:10,n:"Jamonada / mortadela",d:"Pieza",c:"Carnes y Embutidos",p:4600,img:"/products/jamonada.webp"},
{id:11,n:"Queso Gouda en bloque",d:"Bloque",c:"Quesos y Lácteos",p:7850,img:"/products/queso-gouda-bloque.webp"},
{id:12,n:"Queso en lonchas",d:"Bandeja",c:"Quesos y Lácteos",p:7000,img:"/products/queso-lonchas.svg"},
{id:13,n:"Queso crema",d:"Tarrina 200 g",c:"Quesos y Lácteos",p:1600,img:"/products/queso-crema.webp"},
{id:14,n:"Yogur bebible",d:"Botella pequeña",c:"Quesos y Lácteos",p:700,img:"/products/yogur-bebible-pequeno.svg"},
{id:15,n:"Yogur bebible",d:"Botella",c:"Quesos y Lácteos",p:950,img:"/products/yogur-bebible-botella.svg"},
{id:16,n:"Bebida energética",d:"Lata",c:"Bebidas",p:520,img:"/products/energetica-verde.svg"},
{id:17,n:"Néctar Tropical",d:"Goliath · Cartón 1 L",c:"Bebidas",p:1500,img:"/products/nectar-tropical.webp"},
{id:18,n:"Néctar de guayaba",d:"Goliath · Cartón 1 L",c:"Bebidas",p:1500,img:"/products/nectar-guayaba.webp"},
{id:19,n:"Néctar de piña",d:"Goliath · Cartón 1 L",c:"Bebidas",p:1500,img:"/products/nectar-pina.webp"},
{id:20,n:"Jugo de naranja",d:"La Estancia · Cartón 200 mL",c:"Bebidas",p:370,img:"/products/jugo-estancia-naranja.webp"},
{id:60,n:"Néctar de guayaba pequeño",d:"La Estancia · Cartón 200 mL",c:"Bebidas",p:370,img:"/products/jugo-estancia-guayaba.webp"},
{id:21,n:"Jugo Tropical",d:"Mozo Juice · Cartón 200 mL",c:"Bebidas",p:290,img:"/products/jugo-mozo-tropical.webp"},
{id:61,n:"Jugo de mango",d:"Mozo Juice · Cartón 200 mL",c:"Bebidas",p:290,img:"/products/jugo-mozo-mango.webp"},
{id:62,n:"Bebida de frutas sabor rojo",d:"Mozo Juice · Cartón 200 mL",c:"Bebidas",p:290,img:"/products/jugo-mozo-rojo.webp"},
{id:22,n:"KAS Limón",d:"Lata",c:"Bebidas",p:650,img:"/products/kas-limon.svg"},
{id:23,n:"KAS Naranja",d:"Lata",c:"Bebidas",p:650,img:"/products/kas-naranja.svg"},
{id:58,n:"Red Bull",d:"Lata",c:"Bebidas",p:1400,img:"/products/red-bull.svg"},
{id:59,n:"Agua embotellada",d:"Botella",c:"Bebidas",p:300,img:"/products/agua-embotellada.svg"},
{id:24,n:"Heineken",d:"Botella",c:"Cervezas y Vinos",p:890,img:"/products/heineken.webp"},
{id:25,n:"Cristal Extra",d:"Botella",c:"Cervezas y Vinos",p:740,img:"/products/cristal-extra.webp"},
{id:26,n:"Belga Star",d:"Botella 33 cl",c:"Cervezas y Vinos",p:600,img:"/products/belga-star.webp"},
{id:27,n:"Cerveza en lata",d:"Lata",c:"Cervezas y Vinos",p:520,img:"/products/cerveza-lata.webp"},
{id:28,n:"Casillero del Diablo tinto",d:"Concha y Toro · Cabernet Sauvignon",c:"Cervezas y Vinos",p:5900,img:"/products/casillero-tinto.webp"},
{id:29,n:"Casillero del Diablo blanco",d:"Concha y Toro · Sauvignon Blanc",c:"Cervezas y Vinos",p:5900,img:"/products/casillero-blanco.webp"},
{id:30,n:"Frontera Carmenere",d:"Frontera · Botella",c:"Cervezas y Vinos",p:3100,img:"/products/frontera-carmenere.webp"},
{id:31,n:"Frontera Sauvignon Blanc",d:"Frontera · Botella",c:"Cervezas y Vinos",p:2890,img:"/products/frontera-sauvignon.webp"},
{id:32,n:"Frontera Chardonnay",d:"Frontera · Botella",c:"Cervezas y Vinos",p:2800,img:"/products/frontera-chardonnay.webp"},
{id:33,n:"Trapiche Malbec",d:"Trapiche Varietals · Botella",c:"Cervezas y Vinos",p:5540,img:"/products/trapiche-malbec.webp"},
{id:34,n:"Trapiche tinto",d:"Trapiche Vineyards · Malbec",c:"Cervezas y Vinos",p:5510,img:"/products/trapiche-tinto.webp"},
{id:35,n:"Trapiche blanco",d:"Trapiche Vineyards · Botella",c:"Cervezas y Vinos",p:6490,img:"/products/trapiche-blanco.webp"},
{id:36,n:"La Baronne tinto",d:"Botella",c:"Cervezas y Vinos",p:1800,img:"/products/baronne-tinto.webp"},
{id:37,n:"Vino tinto (etiqueta por confirmar)",d:"Botella",c:"Cervezas y Vinos",p:1680,img:"/products/vino-tinto-confirmar.svg"},
{id:38,n:"Jamón cocido en lata",d:"Iberia · Lata",c:"Despensa y Conservas",p:6000,img:"/products/jamon-lata.webp"},
{id:39,n:"Puré de papa",d:"Virna Foods · Bolsa grande",c:"Despensa y Conservas",p:5460,img:"/products/pure-papa.svg"},
{id:40,n:"Bread Crumbs",d:"Iberia · Envase cilíndrico",c:"Despensa y Conservas",p:2900,img:"/products/bread-crumbs.svg"},
{id:41,n:"Lentejas",d:"Peñalba · Bolsa 500 g",c:"Despensa y Conservas",p:850,img:"/products/lentejas.webp"},
{id:42,n:"Frijoles blancos",d:"Peñalba · Bolsa",c:"Despensa y Conservas",p:800,img:"/products/frijoles-blancos.webp"},
{id:43,n:"Frijoles negros",d:"Peñalba · Bolsa 500 g",c:"Despensa y Conservas",p:850,img:"/products/frijoles-negros.webp"},
{id:44,n:"Frijoles",d:"Cibao · Bolsa",c:"Despensa y Conservas",p:1200,img:"/products/frijoles-bolsa-verde.svg"},
{id:45,n:"Aceitunas verdes",d:"Benimar · Lata 2,35 kg",c:"Despensa y Conservas",p:9900,img:"/products/aceitunas-verdes.webp"},
{id:46,n:"Champiñones en conserva",d:"Celorrio · Lata",c:"Despensa y Conservas",p:1300,img:"/products/champinones-lata.webp"},
{id:47,n:"Cinnamon Crisps",d:"Gullón · Caja 200 g",c:"Snacks y Dulces",p:1900,img:"/products/cinnamon-crisps.webp"},
{id:48,n:"Pringles Original",d:"Tubo",c:"Snacks y Dulces",p:1850,img:"/products/pringles.svg"},
{id:63,n:"Papas fritas Lay's",d:"Clásicas · Bolsa 170 g",c:"Snacks y Dulces",p:1500,img:"/products/papas-lays.webp"},
{id:49,n:"Plantain Chips",d:"Fresko · Tarro",c:"Snacks y Dulces",p:8400,img:"/products/plantain-chips.svg"},
{id:50,n:"Plantain Chips",d:"Tarro grande",c:"Snacks y Dulces",p:11500,img:"/products/plantain-chips-grande.svg"},
{id:51,n:"Galletas Oli surtidas",d:"Caja 15 g · sabores variados",c:"Snacks y Dulces",p:1150,img:"/products/oli-surtidas.webp"},
{id:52,n:"Caramelos Mint",d:"Fiesta · Bolsa",c:"Snacks y Dulces",p:2700,img:"/products/caramelos-mint.webp"},
{id:53,n:"Caramelos Éclair",d:"Frutika · Bolsa",c:"Snacks y Dulces",p:2700,img:"/products/caramelos-eclair.webp"},
{id:54,n:"Cappuccino Candy",d:"Fiesta · Bolsa",c:"Snacks y Dulces",p:2700,img:"/products/cappuccino-candy.webp"},
{id:55,n:"Butter Milky Candy",d:"Ricolino · Bolsa",c:"Snacks y Dulces",p:2700,img:"/products/butter-milky-candy.webp"},
{id:56,n:"Coffee Candy",d:"Richto · Bolsa",c:"Snacks y Dulces",p:2700,img:"/products/coffee-candy.webp"},
{id:57,n:"Chocolate Milka",d:"Tableta",c:"Snacks y Dulces",p:2200,img:"/products/chocolate-milka.webp"}
];
